<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_colorblack</name>
   <tag></tag>
   <elementGuidId>fe8fb9e9-ef64-4632-b614-0bc7dea41767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='bunny'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4223141a-a8c0-433a-b283-fd5bfed34d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>BLACK</value>
      <webElementGuid>abe75c09-a70c-486f-b5fa-d9e7539645ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bunny</value>
      <webElementGuid>8554b5fa-fc0a-4529-91c8-38b05343fafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-repeat</name>
      <type>Main</type>
      <value>color in colors</value>
      <webElementGuid>127ac55d-b59d-4971-a7f3-b690664a0252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bunny productColor ng-scope BLACK colorSelected</value>
      <webElementGuid>959cdb4c-d801-436a-852a-c9bf037b41a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>color.code == 'ABCDEF'</value>
      <webElementGuid>7533191c-ebd8-4c16-a31d-a8b38aeb8a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-style</name>
      <type>Main</type>
      <value>color.code == 'FFFFFF' ?
                                          {'backgroundColor': '#' + color.code, 'border': 'solid 1px #9d9d9d' } :
                                          {'backgroundColor': '#' + color.code, 'border': 'solid 1px transparent'}</value>
      <webElementGuid>1b155075-77f4-4e0b-b32c-b62793feb3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ colorSelected : colorSelected.name == color.name , BLACK : colorSelected.name}</value>
      <webElementGuid>87bf9245-accd-4bf2-871f-89c6debd84f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>setColor(color, $event)</value>
      <webElementGuid>923a1ce4-24de-4e2f-9563-7935574726d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productProperties&quot;)/div[@class=&quot;colors ng-scope&quot;]/div[2]/span[@id=&quot;bunny&quot;]</value>
      <webElementGuid>f115ab96-7e3d-4593-a7ad-18beff316175</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='bunny'])[2]</value>
      <webElementGuid>fd3aa030-23c0-438c-a702-a030f71b78e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productProperties']/div/div[2]/span[2]</value>
      <webElementGuid>b4c61d41-4405-474c-ba70-d4064f7298a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color:'])[1]/following::span[8]</value>
      <webElementGuid>ef33ea51-3c93-4ff3-aa96-2cc8ac41a5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[2]/following::span[8]</value>
      <webElementGuid>e63a8530-4c7d-46a5-904e-93bb13b4ae41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/preceding::span[5]</value>
      <webElementGuid>fdef4b1b-c393-4498-a7f3-2323d69f96c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Warranty'])[1]/preceding::span[5]</value>
      <webElementGuid>fe03b701-340e-4786-97b3-f9b486ebcea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>9eaf4302-bdab-4ff7-a390-0adc50c58a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'BLACK' and @id = 'bunny']</value>
      <webElementGuid>cd292824-e658-4e88-9b65-9749d590683d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
