<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_my order profile</name>
   <tag></tag>
   <elementGuidId>f7b8dc4f-e922-4de1-9569-edafd6561dc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginMiniTitle']/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d2ad7251-a080-48fc-a53d-1cf2868e3df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option ng-scope</value>
      <webElementGuid>2a9e6f74-f24a-41a0-9447-af151060f554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>My_Orders</value>
      <webElementGuid>5e064bb6-f0c4-4300-8a2e-bbe645db7bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>mobileRedirect('MyOrders')</value>
      <webElementGuid>b82b9c93-5c85-439c-b43e-222b5bb80de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>8a4d0147-1a1b-4f31-b82d-004c79cd3d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>52c69613-c6a5-490a-9b28-02ca0fed3cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My orders</value>
      <webElementGuid>79875692-7540-441d-b4ca-a67054542935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginMiniTitle&quot;)/label[@class=&quot;option ng-scope&quot;]</value>
      <webElementGuid>fcfc9cd7-f74e-4e17-8616-486d74844794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginMiniTitle']/label[2]</value>
      <webElementGuid>caa42842-3b45-465e-995c-da416361520c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[2]/following::label[1]</value>
      <webElementGuid>2a59d4aa-82dc-4278-beb2-cccb03a46fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admintester'])[2]/following::label[2]</value>
      <webElementGuid>b522e51b-9cff-496e-8583-1e4ba1fd51a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign out'])[2]/preceding::label[1]</value>
      <webElementGuid>65b9bb9e-788c-4a7c-a676-8a49ec8fab21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATEGORIES'])[1]/preceding::label[2]</value>
      <webElementGuid>8ef64448-deb5-4ec4-a580-a4e96a82c41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div/label[2]</value>
      <webElementGuid>5a1d96fd-301c-4154-a76e-51c4614ec8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@href = 'javascript:void(0)' and (text() = 'My orders' or . = 'My orders')]</value>
      <webElementGuid>d2e65f44-4469-4571-9437-c1403bee42b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
