<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_nameprofile</name>
   <tag></tag>
   <elementGuidId>86a811e3-f0d4-4572-8dfc-409d04d229b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.hi-user.containMiniTitle.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menuUserLink']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>db8f7ca0-6bda-4566-a02f-b06beb3b14dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>userCookie.response</value>
      <webElementGuid>89b9970d-3126-44c0-9bca-cd63131ddde0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hi-user containMiniTitle ng-binding</value>
      <webElementGuid>63dac488-feab-4a4d-a3a0-9c8a66292186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>admintester</value>
      <webElementGuid>5100ecf6-9627-4598-b96c-7fbe228c1dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuUserLink&quot;)/span[@class=&quot;hi-user containMiniTitle ng-binding&quot;]</value>
      <webElementGuid>dc3fa392-409d-45e4-ab35-1fcc6137e148</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuUserLink']/span</value>
      <webElementGuid>d9d908db-ffb1-4d79-b891-aa34e2c52011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,728.99'])[1]/following::span[1]</value>
      <webElementGuid>b8ca9255-0389-49be-80d7-fcb3a9def69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[2]/preceding::span[1]</value>
      <webElementGuid>5926dd2c-7b1c-4a81-905b-9fac1bf6a998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My orders'])[2]/preceding::span[1]</value>
      <webElementGuid>1d5ba160-26be-4b56-834f-188ba3d7f312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a/span</value>
      <webElementGuid>224315a4-f09a-4196-bab1-4de5ce905954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'admintester' or . = 'admintester')]</value>
      <webElementGuid>dcbe7772-4dfc-4390-b378-d21b92ed3fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
