<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_paymentsafepay</name>
   <tag></tag>
   <elementGuidId>28951a8f-cda8-4342-b76a-242d8af17746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Safepay&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paymentMethod']/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4916f4a4-bd4b-4b7e-a7a6-6bbe7273a61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/SafePay.png</value>
      <webElementGuid>b610583b-5a6c-4661-bb18-942563b2cd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Safepay</value>
      <webElementGuid>0d70901a-d7ea-4663-bcec-e9bee40e33a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod&quot;)/div[1]/div[@class=&quot;paymentMethods&quot;]/div[@class=&quot;imgRadioButton selected&quot;]/img[1]</value>
      <webElementGuid>d777036f-8baf-4ed9-9b73-c5a8831e3561</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div/div/img</value>
      <webElementGuid>1bdcfad9-fb50-4667-82f4-c8ddef3d9a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose payment method below'])[1]/following::img[1]</value>
      <webElementGuid>c7440efc-c18c-492e-a506-63d3da47dcb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BACK'])[1]/following::img[1]</value>
      <webElementGuid>645530f8-353e-4494-a5e2-26f049314685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notice'])[1]/preceding::img[2]</value>
      <webElementGuid>19ca8b5d-ef5d-4190-96d6-4c87665e6469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::img[2]</value>
      <webElementGuid>ca4cf48e-e295-4912-9dee-93c44ae1b883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Safepay']</value>
      <webElementGuid>e554b152-b6d3-4cc2-a71d-90895316bbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/img</value>
      <webElementGuid>8b24bfa6-b64e-4c62-8b35-5e27332b9d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'css/images/SafePay.png' and @alt = 'Safepay']</value>
      <webElementGuid>32ab5dbc-937e-4cd4-9d4d-28567aacb6d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
