<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_priceshipping</name>
   <tag></tag>
   <elementGuidId>c088abcc-9f17-472e-a301-c1bfe3da716f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shippingCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='shippingCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b0d0fb4-109d-477a-9d4f-2f78e8024307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shippingCost</value>
      <webElementGuid>1977f1e9-0839-418f-9979-2b73560f8dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shippingValue roboto-light ng-binding</value>
      <webElementGuid>23e18508-0925-4290-9a21-c467c07753da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$180.00</value>
      <webElementGuid>dc0d6af8-275a-43d1-9c45-5317b8b9586c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shippingCost&quot;)</value>
      <webElementGuid>68c0ed9c-6a30-4338-ba7b-992a4d21cd1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='shippingCost']</value>
      <webElementGuid>714ecaf8-aa22-4e54-93d0-1cecda62c80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userCart']/div[2]/label/span</value>
      <webElementGuid>e99b5c59-6fb5-4ac9-95ce-6d02bf2906ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,079.98'])[1]/preceding::span[1]</value>
      <webElementGuid>e616e893-fd27-43a2-b548-f6565eb5a873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/span</value>
      <webElementGuid>6f21aa90-e0b4-41d4-8dc1-ecc7e039a76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'shippingCost' and (text() = '$180.00' or . = '$180.00')]</value>
      <webElementGuid>3a3de533-e67e-4223-ba85-f86c780cce00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
