<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_qtycheckout</name>
   <tag></tag>
   <elementGuidId>6f271618-d8f0-4db8-a97f-272aff63e65b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.itemsCount.roboto-medium.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userCart']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ca54ebe8-62e7-4bce-8910-ece5bf0e977e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>itemsCount roboto-medium ng-binding</value>
      <webElementGuid>8d6fad3b-2a1e-47d9-adef-b50decd1b1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2 ITEMS</value>
      <webElementGuid>70af97d8-7726-4f51-8c0a-11b90a67f0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userCart&quot;)/span[@class=&quot;itemsCount roboto-medium ng-binding&quot;]</value>
      <webElementGuid>7cdd69b1-8e5e-47ce-9412-f9c83c662d13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userCart']/span</value>
      <webElementGuid>320e2fac-cc39-4e55-920b-ec3feea56ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDER SUMMARY'])[1]/following::span[1]</value>
      <webElementGuid>1119fdbf-2982-4d38-9ccc-c25605b0b60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAY NOW'])[3]/following::span[1]</value>
      <webElementGuid>906be0bc-65d2-405e-87d8-6e5350b47be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT'])[1]/preceding::span[1]</value>
      <webElementGuid>89dd3d66-1c2e-4d9a-aa6c-daa09c22d682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL'])[1]/preceding::span[2]</value>
      <webElementGuid>5b0ef58d-9e6c-4b27-a5b5-67c91c0418ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>5dad55a4-cd00-42a5-9922-e07b21da6690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '2 ITEMS' or . = '2 ITEMS')]</value>
      <webElementGuid>a7b01019-5ade-4268-a063-f035afd31929</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
