<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_totalprice</name>
   <tag></tag>
   <elementGuidId>3a6d312e-0de1-4530-a4db-2a16bbac80b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.roboto-medium.totalValue.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userCart']/div[2]/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6e0531c2-feab-4b0c-adc8-79d7559623e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium totalValue ng-binding</value>
      <webElementGuid>e7125771-f001-4864-b496-66529d37b85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$1,079.98</value>
      <webElementGuid>6a4f2052-3815-40ce-9b09-085fb32b1911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userCart&quot;)/div[@class=&quot;penetrationInCart&quot;]/label[@class=&quot;roboto-bold totalText ng-binding&quot;]/span[@class=&quot;roboto-medium totalValue ng-binding&quot;]</value>
      <webElementGuid>c266b7b8-c445-45a2-87ec-e65d43862cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userCart']/div[2]/label[2]/span</value>
      <webElementGuid>5593e423-e815-45ce-9304-836bffc1b1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$180.00'])[1]/following::span[1]</value>
      <webElementGuid>96ee4ef1-056b-42f7-b404-36e8ed25cd2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you for buying with Advantage'])[1]/preceding::span[1]</value>
      <webElementGuid>8446f9f3-f384-4170-989a-21b8a461deeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::span[2]</value>
      <webElementGuid>bd82bf76-a770-453d-9677-0cb904e03e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label[2]/span</value>
      <webElementGuid>d3d553b3-4d4e-4708-b6bd-a7699a0b5de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$1,079.98' or . = '$1,079.98')]</value>
      <webElementGuid>2384131c-a5f5-460a-ade2-595fbebe1ae7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
