<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_ordernumber</name>
   <tag></tag>
   <elementGuidId>4e9deeb3-227a-4356-b97e-80592b47d34e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#orderNumberLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='orderNumberLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f2f05274-6442-43a1-b687-04bd2ed966bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>orderNumberLabel</value>
      <webElementGuid>fae58fd9-1544-4f9b-b3ac-201d99e9f285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>640d874a-c408-40f5-8093-59f958264891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1496420317</value>
      <webElementGuid>16ae8780-382b-448c-9bc2-3a00b3987735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderNumberLabel&quot;)</value>
      <webElementGuid>1bd09e93-52de-4168-bee3-6c06dcd2fc57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='orderNumberLabel']</value>
      <webElementGuid>cfde5e67-6045-4144-9f99-4bfe9fc53938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderPaymentSuccess']/p/label[2]</value>
      <webElementGuid>7d6c71d9-2a7d-4a9e-9413-25e191c8aea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::label[1]</value>
      <webElementGuid>b9f3617c-0b8c-4dcf-b531-f3dea4126ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you for buying with Advantage'])[1]/following::label[2]</value>
      <webElementGuid>8ee0adf7-a48b-4af8-b2c7-f9bc4269f43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/preceding::label[1]</value>
      <webElementGuid>eaeb26a8-c4cd-4976-99ff-4a8093b44608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your warranty number is'])[1]/preceding::label[1]</value>
      <webElementGuid>e0d58cc0-61c8-4840-bd8b-2424bc81c396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/label[2]</value>
      <webElementGuid>8774b7d2-bf58-4c8c-a7c7-8498adeab413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'orderNumberLabel' and (text() = '1496420317' or . = '1496420317')]</value>
      <webElementGuid>8b17fd5d-cf75-4e90-b29b-7d1e83900d56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
