<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_trackingnumber</name>
   <tag></tag>
   <elementGuidId>6b5cd1c6-5037-4d59-874d-2baab50c1980</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trackingNumberLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='trackingNumberLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a3a22a05-bb76-45c1-bb5d-f3e33af0dd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trackingNumberLabel</value>
      <webElementGuid>f60d8ef7-22c2-481d-b72c-d1ffbfd14319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>1a65ad3a-f4bd-4583-9143-5c0814e2861b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1496386888</value>
      <webElementGuid>77bbbd93-9bd3-4968-b82e-2dc24a505b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trackingNumberLabel&quot;)</value>
      <webElementGuid>074060e6-0204-42f4-98c3-e175dd9541d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='trackingNumberLabel']</value>
      <webElementGuid>ea870738-00ea-4960-bd76-2d70f34000bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderPaymentSuccess']/p/label</value>
      <webElementGuid>58895d17-90d9-4bab-af55-4679d275cbc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you for buying with Advantage'])[1]/following::label[1]</value>
      <webElementGuid>69276d91-620e-433d-ac7f-a272f2db0ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[4]/following::label[1]</value>
      <webElementGuid>51284fa5-fd1f-4040-8ddf-4edd77802e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::label[1]</value>
      <webElementGuid>3c1f8acc-679b-4e7b-9203-9b4c06faef59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/preceding::label[2]</value>
      <webElementGuid>3dcf6541-83b6-45da-a7c0-948ad8a3e4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/label</value>
      <webElementGuid>a39bdcb7-e318-40a8-808a-834254b4e37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'trackingNumberLabel' and (text() = '1496386888' or . = '1496386888')]</value>
      <webElementGuid>f3b392de-f812-447c-8a04-5005ae0f242d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
