<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_nameproduct1</name>
   <tag></tag>
   <elementGuidId>b18f13e7-67ce-4070-bc8e-5aba00b7b498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//tr[@id='product']/td[2]/a/h3)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>e3d86c4b-3351-4292-a99f-972ac8c8bc08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>563f5d8f-d187-4194-99a6-2184d44282ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HP PAVILION 15Z TOUCH LAPTOP</value>
      <webElementGuid>c92a4ffc-5fb1-45bf-a83c-c61811cde035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userCart&quot;)/tool-tip-cart[@id=&quot;toolTipCart&quot;]/div[1]/table[1]/tbody[1]/tr[@id=&quot;product&quot;]/td[2]/a[1]/h3[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>c43d18df-9c5d-418d-8e5f-202fe20df3ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='product']/td[2]/a/h3)[3]</value>
      <webElementGuid>f3d620ee-a3ea-4a7a-885e-ccc3eefa7478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your shopping cart is empty'])[2]/following::h3[1]</value>
      <webElementGuid>1e162911-fdde-49cf-8b3a-58a19b5b87f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[2]/following::h3[1]</value>
      <webElementGuid>ff47a0d5-442f-4703-8428-ea4d3d09510a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QTY: 1'])[3]/preceding::h3[1]</value>
      <webElementGuid>0094c21f-4850-47bd-aaf3-acd506e34237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/tool-tip-cart/div/table/tbody/tr/td[2]/a/h3</value>
      <webElementGuid>f1402604-9ebf-4d53-9ddb-da1bf05a079c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'HP PAVILION 15Z TOUCH LAPTOP' or . = 'HP PAVILION 15Z TOUCH LAPTOP')]</value>
      <webElementGuid>b3ce6e03-32a5-415e-a233-a49cd3f18596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
