<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_order number</name>
   <tag></tag>
   <elementGuidId>7fadb1ef-e2f9-4520-8bff-e9a6af5d91fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > label.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myAccountContainer']/div/table/tbody/tr[2]/td/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>db31f1b4-c2a4-4fda-8c5e-ff60c29a0591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>fcfe56fe-ee48-4ade-bcbf-4c249d966349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1496420134</value>
      <webElementGuid>97c6ed8d-02d9-4f7c-a0e4-595b9cb3953b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountContainer&quot;)/div[@class=&quot;cover&quot;]/table[1]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[1]/label[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>845ac4e0-5b77-4c64-a455-c0d3710255e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAccountContainer']/div/table/tbody/tr[2]/td/label</value>
      <webElementGuid>941405be-44e2-4f55-a3fa-ea64243ebc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL PRICE'])[1]/following::label[1]</value>
      <webElementGuid>c1e1546e-6ed8-457f-bbe1-40c5f730ef57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUANTITY'])[1]/following::label[2]</value>
      <webElementGuid>869a6598-fb32-4021-b10d-ac974b9d2eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HP Pavilion 15z Touch Laptop'])[1]/preceding::label[3]</value>
      <webElementGuid>c8baed0d-cdf6-40ca-82a6-e2df5623651c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$899.98'])[1]/preceding::label[4]</value>
      <webElementGuid>1b0dd6f5-8756-47c7-a8a9-6364bbfaa381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/label</value>
      <webElementGuid>b5055c80-dba3-4f47-abaf-d8f023c411f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '1496420134' or . = '1496420134')]</value>
      <webElementGuid>edf1eabb-444c-4626-a14f-f7734d056fde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
