<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_checkout</name>
   <tag></tag>
   <elementGuidId>15154a69-2019-4934-b928-c01af8044edc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkOutButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkOutButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ddd85af8-bae0-46ff-973c-9b14d78e0e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9fda599-af90-4095-a62a-515e2781d854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium tami uft-class ng-binding</value>
      <webElementGuid>c73da9a9-ff6a-4a76-a252-65c46c0ada34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>checkout()</value>
      <webElementGuid>5d9bc2c7-0d70-4114-bc81-e8d29adb97bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkOutButton</value>
      <webElementGuid>3046cac5-60d2-4120-8857-741fab250363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check_out_btn</value>
      <webElementGuid>e6f25138-ba8d-4557-822d-b3ec0f7ecaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT ($899.98)</value>
      <webElementGuid>cb04d269-34b6-4856-b4e2-853d5a0bc962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkOutButton&quot;)</value>
      <webElementGuid>fae34740-a5e8-4a1a-b16d-c062a6d3b2df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkOutButton']</value>
      <webElementGuid>b2af5e36-53b8-4565-8a3c-57dfaab3d5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shoppingCart']/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>ea9467da-9fec-4402-9eec-9e2eb3f5c18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$899.98'])[2]/following::button[1]</value>
      <webElementGuid>a283f88f-fa1b-4628-a783-87998cc16874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL:'])[1]/following::button[1]</value>
      <webElementGuid>d201b90f-7a71-4af8-b489-69d8117a6cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your shopping cart is empty'])[2]/preceding::button[1]</value>
      <webElementGuid>58d24527-9987-415a-afc1-b98613ce424d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUE SHOPPING'])[1]/preceding::button[1]</value>
      <webElementGuid>08e121df-92a8-40e2-8809-5304e979540a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>12469749-08c7-492e-9df7-30d3d1d6e1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'checkOutButton' and @name = 'check_out_btn' and (text() = 'CHECKOUT ($899.98)' or . = 'CHECKOUT ($899.98)')]</value>
      <webElementGuid>47ce9e7d-5b65-4a98-a6dd-312bda59bb3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
