<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_cartcolor1</name>
   <tag></tag>
   <elementGuidId>d0896a81-c9d2-4680-9f46-dd027ac91e92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.productColor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shoppingCart']/table/tbody/tr/td[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b2b645aa-bfe9-4bfb-971e-31ddaa299c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>GRAY</value>
      <webElementGuid>8dddd5bb-6bdc-4930-87b5-3e0c580d2795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>product.color.code != 'FFFFFF' ? {'backgroundColor': '#' + product.color.code, 'border': 'none 0px white'} : { 'backgroundColor': '#' + product.color.code }</value>
      <webElementGuid>2b81fbd9-47e2-4dd7-af8b-98774636bab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productColor</value>
      <webElementGuid>1d93664b-f671-4856-af3c-a8bf79f90cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shoppingCart&quot;)/table[@class=&quot;fixedTableEdgeCompatibility&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;smollCell&quot;]/span[@class=&quot;productColor&quot;]</value>
      <webElementGuid>9f7aaafd-040a-4b2d-af7a-2f43a4b8a553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shoppingCart']/table/tbody/tr/td[4]/span</value>
      <webElementGuid>d3f0eb5e-5972-4a76-be1f-65a672d9841e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COLOR:'])[1]/following::span[1]</value>
      <webElementGuid>9028999f-d430-40e6-961a-8aa8f9c758fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WARRANTY'])[2]/following::span[1]</value>
      <webElementGuid>c4f8b60d-54a6-45b2-b6c4-56e03d99e93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUANTITY'])[2]/preceding::span[1]</value>
      <webElementGuid>9506aa53-7f80-4899-8562-0b275d21441d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRICE:'])[1]/preceding::span[1]</value>
      <webElementGuid>fadb4a9a-3fba-48c3-bfd7-525f6d3baa40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/span</value>
      <webElementGuid>1d87aec6-9ec0-4b88-bafe-dd904a743d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'GRAY']</value>
      <webElementGuid>dc434fa8-33d1-4a38-a290-939b9197ab11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
