<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_countcart</name>
   <tag></tag>
   <elementGuidId>8eba599e-895b-46c9-be6b-daee1ee0525b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shoppingCartLink > span.cart.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='shoppingCartLink']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>48c32423-b77c-4a33-bc9c-49983ac74b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart ng-binding</value>
      <webElementGuid>f17d9465-0676-43a7-8d2f-cad19b3725a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>(cart | productsCartCount) > 0</value>
      <webElementGuid>dd52f940-ba7e-41e1-aeb5-45e4122547ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0da714b2-9685-4c5b-95e8-5da6cfeb1e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shoppingCartLink&quot;)/span[@class=&quot;cart ng-binding&quot;]</value>
      <webElementGuid>076e8b7f-e77d-46c5-8254-1a4f1d64e474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='shoppingCartLink']/span</value>
      <webElementGuid>a7cfd080-f26e-420d-ad21-e0144d879523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management Console'])[2]/following::span[1]</value>
      <webElementGuid>324e4c0a-6ecf-4d08-b2da-8fb2c97c92d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AOS Versions'])[2]/following::span[1]</value>
      <webElementGuid>fe60a948-af41-41d5-bac9-3cb824f85b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[1]/preceding::span[1]</value>
      <webElementGuid>7f698dc4-99e6-4ecf-aacb-314595d83540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a/span</value>
      <webElementGuid>652138b2-ef96-462e-b1f9-e218c11189bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '2' or . = '2')]</value>
      <webElementGuid>03740bb4-e383-46e1-9ab6-910fa63e47a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
