<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_cartprice1</name>
   <tag></tag>
   <elementGuidId>99d425d4-f126-412f-876c-267909183454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.smollCell > p.price.roboto-regular.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shoppingCart']/table/tbody/tr/td[6]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>02b3bd14-0c9b-42cb-80da-f041695ac53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price roboto-regular ng-binding</value>
      <webElementGuid>a15554b6-af30-4eee-879b-f1012b463541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            $449.99
                        </value>
      <webElementGuid>fcac3393-4272-49c3-8ba1-46979f27a8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shoppingCart&quot;)/table[@class=&quot;fixedTableEdgeCompatibility&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;smollCell&quot;]/p[@class=&quot;price roboto-regular ng-binding&quot;]</value>
      <webElementGuid>3b088f90-3dcd-4c08-8863-765c31a430b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shoppingCart']/table/tbody/tr/td[6]/p</value>
      <webElementGuid>ba533526-c648-415c-95ef-4d77ddf03573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRICE:'])[1]/following::p[1]</value>
      <webElementGuid>3b3f6f01-31f8-4cee-b39c-99aa47a2ddde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUANTITY'])[2]/following::p[1]</value>
      <webElementGuid>2a82a93e-894a-42a2-8df5-09b8fbdd60f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDIT'])[1]/preceding::p[1]</value>
      <webElementGuid>3aa1e651-6449-40a0-8085-6ea9efd1407e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::p[1]</value>
      <webElementGuid>4f4c0a97-ce11-4af2-9064-3ddc4b76f91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/p</value>
      <webElementGuid>9d954870-c0a5-45ba-a16f-698bc2ed079d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
                            $449.99
                        ' or . = '
                            $449.99
                        ')]</value>
      <webElementGuid>701887e6-bdbc-48f4-8007-9ed68b95868f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
