<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_editprofile</name>
   <tag></tag>
   <elementGuidId>0b8a4ee4-b793-40cb-af6a-3759dbcb8044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myAccountContainer']/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.floatRigth.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ab1a0fb-88e2-47a3-84b6-3dfb744456fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floatRigth ng-scope</value>
      <webElementGuid>2957995a-7e70-46e4-8ea6-05eed93f81c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/accountDetails</value>
      <webElementGuid>faccb26a-4e61-4868-a5bd-64251b5bb074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>5940fdc4-6912-42a7-a3de-1b6526e1ac48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>e020fcb2-15c2-4268-a460-0c56342610a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountContainer&quot;)/div[@class=&quot;cube&quot;]/h3[@class=&quot;blueLink ng-binding&quot;]/a[@class=&quot;floatRigth ng-scope&quot;]</value>
      <webElementGuid>c3dccaa8-a1b5-42a7-9ad1-e37586047d20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAccountContainer']/div/h3/a</value>
      <webElementGuid>d95683be-8eae-4e69-9312-4eb9543a57e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>12b06971-535f-4632-85b0-7c6b1d5b2f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MY ACCOUNT'])[2]/following::a[1]</value>
      <webElementGuid>46c3cd33-3458-44c6-a432-d8211a957557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin admin'])[1]/preceding::a[2]</value>
      <webElementGuid>3618b5be-1478-4352-bf97-0019505a83e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/preceding::a[2]</value>
      <webElementGuid>ca8591fb-140a-44e7-b190-3c00083d1483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/accountDetails')]</value>
      <webElementGuid>8bd3b348-0f6c-436b-add0-29e88529ddc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>424cdcdf-5a3a-46fc-a4fb-5b97c67c60fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/accountDetails' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>0672e4cb-7b84-4d7b-9e3d-8e782da5dda0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
